CREATE DATABASE IF NOT EXISTS BANKDATA;
USE BANKDATA;

---CREATING SCHEMA FOR ALL THE 3 LAYERS
CREATE SCHEMA IF NOT EXISTS BANKDATA.RAW;
CREATE SCHEMA IF NOT EXISTS BANKDATA.REFINED;
CREATE SCHEMA IF NOT EXISTS BANKDATA.REPORTING;


---CREATING STORAGE INTEGRATION

CREATE OR REPLACE STORAGE INTEGRATION azure_bank_integration_snowpipe
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('azure://saadlsbankdestination.blob.core.windows.net/bankdata/
')
  AZURE_TENANT_ID = 'dd822e28-c800-45d7-ad1a-b705256c9466';


---DESCRIBE INTEGRATION OBJECT TO PROVIDE ACCESS
DESC STORAGE integration azure_bank_integration_snowpipe;


---CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT BANKDATA.PUBLIC.FILEFORMAT_CSV
TYPE=CSV
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


--- CREATING NOTIFICATION INTEGRATION
CREATE OR REPLACE NOTIFICATION INTEGRATION snowpipe_event
  ENABLED = true
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://saadlsbankdestination.queue.core.windows.net/snowpipequeue'
  AZURE_TENANT_ID = 'dd822e28-c800-45d7-ad1a-b705256c9466';
  
  
  -- Register Integration
  
DESC notification integration snowpipe_event;
----------------------------------CUSTOMERS--------------------------------------------------

---CREATE A BANK_CUSTOMERS STAGE OBJECT
CREATE OR REPLACE STAGE BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMERS
STORAGE_INTEGRATION = azure_bank_integration_snowpipe
URL='azure://saadlsbankdestination.blob.core.windows.net/bankdata/Bank_Customers/'
FILE_FORMAT=FILEFORMAT_CSV;

---LIST FILES
LIST @BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMERS;

---CREATING BANK_CUSTOMERS TABLE 

CREATE OR REPLACE TABLE BANKDATA.RAW.RAW_BANK_CUSTOMERS (
  "CUSTOMER_ID" STRING,
  "FIRST_NAME" STRING,
  "LAST_NAME" STRING,
  "PHONE_NUMBER" STRING,
  "EMAIL" STRING,
  "AGE" STRING,
  "GENDER" STRING,
  "MARITAL_STATUS" STRING,
  "ADDRESS" STRING,
  "EMPLOYMENT_STATUS" STRING,
  "INCOME(MONTH)" STRING,
  "PAN_NUMBER" STRING,
  "ACCOUNT_NUMBER" STRING,
  "CIBIL_SCORE" STRING,
  "NUMBER_OF_DEPENDENTS" STRING
);



select $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15 from @bankdata.public.STAGE_AZURE_BANK_CUSTOMERS;

select * from BANKDATA.RAW.RAW_BANK_CUSTOMERS;

-- Example: Create Snowpipe for CUSTOMERS table

CREATE  or replace PIPE BANKDATA.RAW.CUSTOMERS_PIPE
AUTO_INGEST = TRUE 
integration= 'SNOWPIPE_EVENT'
AS
COPY INTO BANKDATA.RAW.RAW_BANK_CUSTOMERS
FROM @BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMERS
FILE_FORMAT = (FORMAT_NAME = BANKDATA.PUBLIC.FILEFORMAT_CSV),
PATTERN = '.*Bank_Customers.*\.csv'
;


SELECT count(*) FROM BANKDATA.RAW.RAW_BANK_CUSTOMERS;
SELECT * FROM BANKDATA.RAW.RAW_BANK_CUSTOMERS;

select SYSTEM$PIPE_STATUS('BANKDATA.RAW.CUSTOMERS_PIPE');

------------------------------------LOANS---------------------------------------------------

---CREATE A BANK_LOANS STAGE OBJECT
CREATE OR REPLACE STAGE BANKDATA.PUBLIC.STAGE_AZURE_BANK_LOANS
STORAGE_INTEGRATION = azure_bank_integration_snowpipe
URL='azure://saadlsbankdestination.blob.core.windows.net/bankdata/Bank_Loans/'
FILE_FORMAT=FILEFORMAT_CSV;

---LIST FILES
LIST @BANKDATA.PUBLIC.STAGE_AZURE_BANK_LOANS;

---CREATING LOANS TABLE
CREATE OR REPLACE TABLE BANKDATA.RAW.RAW_BANK_LOANS (
  "LOAN_ID" STRING,
  "CUSTOMER_ID" STRING,
  "LOAN_AMOUNT" STRING,
  "LOAN_TYPE" STRING,
  "RATE_OF_INTEREST" STRING,
  "EMI" STRING,
  "TERM_MONTHS" STRING,
  "LOAN_STATUS" STRING,
  "ISSUE_DATE" STRING
);


SELECT * FROM BANKDATA.RAW.RAW_BANK_LOANS;

select $1,$2,$3,$4,$5,$6 from @bankdata.public.STAGE_AZURE_BANK_LOANS;


-- Example: Create Snowpipe for LOANS table

CREATE  or replace PIPE BANKDATA.RAW.LOANS_PIPE
AUTO_INGEST = TRUE 
integration= 'SNOWPIPE_EVENT'
AS
COPY INTO BANKDATA.RAW.RAW_BANK_LOANS
FROM @BANKDATA.PUBLIC.STAGE_AZURE_BANK_LOANS
FILE_FORMAT = (FORMAT_NAME = BANKDATA.PUBLIC.FILEFORMAT_CSV)
;
-----------------------------------PAYMENTS--------------------------------------------------


---CREATE A BANK_PAYMENTS STAGE OBJECT
CREATE OR REPLACE STAGE BANKDATA.PUBLIC.STAGE_AZURE_BANK_PAYMENTS
STORAGE_INTEGRATION = azure_bank_integration_snowpipe
URL='azure://saadlsbankdestination.blob.core.windows.net/bankdata/Bank_Payments/'
FILE_FORMAT=FILEFORMAT_CSV;

---LIST FILES
LIST @BANKDATA.PUBLIC.STAGE_AZURE_BANK_PAYMENTS;

CREATE OR REPLACE TABLE BANKDATA.RAW.RAW_BANK_PAYMENTS (
  "PAYMENT_ID" STRING,
  "LOAN_ID" STRING,
  "DUE_DATE" STRING,
  "PAID_DATE" STRING,
  "AMOUNT_PAID" STRING,
  "STATUS" STRING
);


select $1,$2,$3,$4,$5 from @bankdata.public.STAGE_AZURE_BANK_PAYMENTS; 

CREATE  or replace PIPE BANKDATA.RAW.PAYMENTS_PIPE
AUTO_INGEST = TRUE 
integration= 'SNOWPIPE_EVENT'
AS
COPY INTO BANKDATA.RAW.RAW_BANK_PAYMENTS
FROM @bankdata.public.STAGE_AZURE_BANK_PAYMENTS
FILE_FORMAT = (FORMAT_NAME = BANKDATA.PUBLIC.FILEFORMAT_CSV);

SELECT COUNT(*) FROM BANKDATA.RAW.RAW_BANK_PAYMENTS;


--------------------------------ASSETS--------------------------------------------

---CREATE A BANK_CUSTOMER_ASSETS STAGE OBJECT
CREATE OR REPLACE STAGE BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMER_ASSETS
STORAGE_INTEGRATION = azure_bank_integration_snowpipe
URL='azure://saadlsbankdestination.blob.core.windows.net/bankdata/Bank_Customer_Assets/'
FILE_FORMAT=FILEFORMAT_CSV;

---LIST FILES
LIST @BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMER_ASSETS;

CREATE OR REPLACE TABLE BANKDATA.RAW.RAW_BANK_CUSTOMER_ASSETS (
  "ASSET_ID" STRING,
  "CUSTOMER_ID" STRING,
  "ASSET_NAME" STRING,
  "ASSET_WORTH" STRING
);

SELECT $1,$2,$3,$4 FROM @bankdata.public.STAGE_AZURE_BANK_CUSTOMER_ASSETS;


CREATE  or replace PIPE BANKDATA.RAW.CUSTOMER_ASSETS_PIPE
AUTO_INGEST = TRUE 
integration= 'SNOWPIPE_EVENT'
AS
COPY INTO BANKDATA.RAW.RAW_BANK_CUSTOMER_ASSETS
FROM @BANKDATA.PUBLIC.STAGE_AZURE_BANK_CUSTOMER_ASSETS
FILE_FORMAT = (FORMAT_NAME = BANKDATA.PUBLIC.FILEFORMAT_CSV)
;

SELECT * FROM BANKDATA.RAW.RAW_BANK_CUSTOMER_ASSETS;


SELECT SYSTEM$PIPE_STATUS('BANKDATA.RAW.CUSTOMER_ASSETS_PIPE');

DESC NOTIFICATION INTEGRATION snowpipe_event;

